name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/qcgames
  - type: dropdown
    id: package
    attributes:
      label: Which server is this bug report for?
      options:
        - Murderer's Arena
        - Doki Doki Murder
        - Québec Murder
        - All
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce the bug: (Provide specific, clear, and concise steps for us to reliably reproduce this issue.)
        1. do thing
        2. observe behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What is the behavior you expect to occur that is not?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: What is the behavior you are currently seeing instead?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video demonstrating the issue being experienced.
    validations:
      required: false
